In [9]:
import numpy as np

In [10]:
a=np.array([[[1,2,6],[3,4,5],[34,36,35]],[[8,9,0],[11,12,13],[56,57,58]]]) #Declaring 3d matrix
print(a)

[[[ 1  2  6]
  [ 3  4  5]
  [34 36 35]]

 [[ 8  9  0]
  [11 12 13]
  [56 57 58]]]


In [11]:
a.shape #where 2 is the number of 2D matrices, 3 is the number of rows in each 2D matrix, and 3 is the number of columns in each 2D matrix

(2, 3, 3)

In [12]:
a.ndim

3

In [13]:
a.nbytes #total bytes occupied by elements

72

In [17]:
a[0,1,1] #from 1st 2d matrix gives 1st row and 1st col indexwise

4

In [22]:
a[:,2,:] #gives 2nd row and each col of each 2d matrix

array([[34, 36, 35],
       [56, 57, 58]])