In [49]:
import numpy as np
a=np.array([[1,2,3,0,7,8,9,99],[5,6,7,8,33,56,78,98]])
print(a)

[[ 1  2  3  0  7  8  9 99]
 [ 5  6  7  8 33 56 78 98]]


In [50]:
#get a specified element  a [row no. , col no.]
print(a[0,0])
print(a[1,0])
print(a[1,3])

1
5
8


In [51]:
#get a specific row
a[0,:]

array([ 1,  2,  3,  0,  7,  8,  9, 99])

In [52]:
#specific col
a[:,1] #got 2nd col but its index is 1

array([2, 6])

In [53]:
a[0,0:7:2] #give row 1 with step size of 2 and starting index=0 and ending index=7 for 1st row

array([1, 3, 7, 9])

In [54]:
a[0,1]=6
print(a)

[[ 1  6  3  0  7  8  9 99]
 [ 5  6  7  8 33 56 78 98]]
