In [2]:
import numpy as np

In [3]:
np.zeros((2,5,5)) #zero matrix of whatever shape given

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [5]:
a=np.ones((2,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]]


In [5]:
np.full((3,4),5) #3 by 4 2-d matrix where each element is 5

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [6]:
np.random.rand(2,3) #random float numbers

array([[0.01246059, 0.3491367 , 0.58903173],
       [0.16874535, 0.97886864, 0.49933449]])

In [7]:
np.random.random_sample(a.shape) #to assign another matrix shape

array([[0.19226067, 0.85028996, 0.24147273],
       [0.68848088, 0.37094799, 0.22187124]])

In [8]:
#matrix with any random integer from -100 to 100 of size 3*4
np.random.randint(-100,101,size=(3,4))

array([[   5,  -66, -100,  -42],
       [  29,   69,  -61,   -7],
       [ -55,   44,  -20,   49]])

In [9]:
np.identity(3) #identity matrix has size m*m

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
a=np.ones((5,5)) #exercise1
print(f"{a}{"\n"}")
z=np.zeros((3,3))
print(z)
z[1,1]=9
print(z)
print("\n")
a[1:-1,1:-1]=z
print(a.astype(int))

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]


[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


## Be careful while copying matrices

In [33]:
a=np.array([[1,2,3],[3,4,5]])
b=a
print(b)
print("\n")
b[0,0]=100
print(b)
print("\n")
print(f"{a}\n") #This will also give same matrix as b so we use copy function
b=a.copy()
b[0,0]=1
print(f"{b}\n")
print(a)

[[1 2 3]
 [3 4 5]]


[[100   2   3]
 [  3   4   5]]


[[100   2   3]
 [  3   4   5]]

[[1 2 3]
 [3 4 5]]

[[100   2   3]
 [  3   4   5]]


In [29]:
#Same goes for list
h=[1,2,3,4,5]
k=h
k[0]=100
print(f"{k}\n")
print(h)
k=h.copy()
print(k)
k[0]=1
print(k)
print(h)

[100, 2, 3, 4, 5]

[100, 2, 3, 4, 5]
[100, 2, 3, 4, 5]
[1, 2, 3, 4, 5]
[100, 2, 3, 4, 5]
