In [3]:
import numpy as np

In [7]:
a=np.array([[1,2,3,4,45],[7,8,9,10,1]])
b=np.array([[7,8,9,1,11],[4,5,6,7,1]])
print(a+b)
print(a/b)
print(a*b) #matmul will give error here as no of cuolumn of a is not equal to no of rows of b

[[ 8 10 12  5 56]
 [11 13 15 17  2]]
[[0.14285714 0.25       0.33333333 4.         4.09090909]
 [1.75       1.6        1.5        1.42857143 1.        ]]
[[  7  16  27   4 495]
 [ 28  40  54  70   1]]


In [23]:
#if matrices are of size m*n and n*j then multiplication:
c=np.array([[1,2,3],[5,6,7]])
d=np.array([[1,2,3,4],[7,8,9,0],[55,666,77,88]])
print(f"{c}\n{d}")
print(np.matmul(c,d)) #resultant matrix of 2*4

[[1 2 3]
 [5 6 7]]
[[  1   2   3   4]
 [  7   8   9   0]
 [ 55 666  77  88]]
[[ 180 2016  252  268]
 [ 432 4720  608  636]]


In [24]:
#find determinant
matrix = np.array([[1, 2], [3, 4]])  # Example matrix
det = np.linalg.det(matrix)
print("Determinant:", det)

Determinant: -2.0000000000000004


In [25]:
#inreverse
if np.linalg.det(matrix) != 0:  # Check if the matrix is invertible
    inverse = np.linalg.inv(matrix)
    print("Inverse:\n", inverse)
else:
    print("Matrix is singular and not invertible.")

Inverse:
 [[-2.   1. ]
 [ 1.5 -0.5]]


In [26]:
#find eigan calues and vector
print (np.linalg.eig(matrix))

EigResult(eigenvalues=array([-0.37228132,  5.37228132]), eigenvectors=array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))


In [27]:
#Reprganising matrices
o=np.array([[1,2,3,4],[5,6,7,8]])
print(o)
k=o.reshape((8,1))
print(k)
print(o.reshape((4,2)))
print("\n")
print(o.reshape((2,2,2)))

[[1 2 3 4]
 [5 6 7 8]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [28]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Stack them vertically
C = np.vstack((A, B))

print("Vertically stacked matrix:")
print(C)

Vertically stacked matrix:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [29]:
A = np.array([[1, 2,3,4], [9, 0,11,12]])
B = np.array([[5, 6], [7, 8]])

# Stack them horizontally
D = np.hstack((A, B))

print("Horizontally stacked matrix:")
print(D)

Horizontally stacked matrix:
[[ 1  2  3  4  5  6]
 [ 9  0 11 12  7  8]]


## getting data from file

In [34]:
file=np.genfromtxt('random_numbers.txt')
file=file.astype(int)
print(file)

[ 16  25  51  31  53  22  29   5  84  52  79  50  76  41  99  59  34  27
  52  71  65   9  22  17  32  48  64  34  17  55  59  31  31  19  57  87
  82  48  77  81  69  63  24  15 100   7  51  52  24  35  95  64  84   1
  71  51  53  48 100   1  49  45   8   2  89  21  55  97  38  41  22  83
  60  44   3  72   7  37  75  97  49  28  41  35  59  73  52  89  37  11
  37  76  89  25  77  84  77   7  55  49]


In [45]:
print(file>50) #shows value true or false
print(file[file>50])

[False False  True False  True False False False  True  True  True False
  True False  True  True False False  True  True  True False False False
 False False  True False False  True  True False False False  True  True
  True False  True  True  True  True False False  True False  True  True
 False False  True  True  True False  True  True  True False  True False
 False False False False  True False  True  True False False False  True
  True False False  True False False  True  True False False False False
  True  True  True  True False False False  True  True False  True  True
  True False  True False]
[ 51  53  84  52  79  76  99  59  52  71  65  64  55  59  57  87  82  77
  81  69  63 100  51  52  95  64  84  71  51  53 100  89  55  97  83  60
  72  75  97  59  73  52  89  76  89  77  84  77  55]
