In [3]:
print("hello")

hello


In [4]:
import numpy as np

In [5]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
print(a*b)
print(f"Addition of these two array is: {a+b}")

[ 5 12 21 32]
Addition of these two array is: [ 6  8 10 12]


In [6]:
#2-D array
c=np.array([[1,2,3],[4,5,6]])
print(c)
#get shape of array
print(c.shape)
print(a.shape)  #a is 1d array
print(b.ndim)  #dimension of array b

[[1 2 3]
 [4 5 6]]
(2, 3)
(4,)
1


In [7]:
a.itemsize #number of bytes occupied by one item in array

4

In [8]:
d=np.array([1,2,3])
d.size #to get number of elements

3

In [9]:
print(d.size * d.itemsize)   #number of bytes or space occupied by array d
# or could be done by:
print(d.nbytes)

12
12
